### PR TITLE
Add a setting to allow for custom tailwind source repo

### PR DESCRIPTION
**Pull request by Tobi-De**
#128

### CODE REVIEW

**Comment by Tobi-De** [comment]
Sorry @oliverandrich  the commit history is messed up because of me, I though you were going to squash and merge 😅

**Comment by Tobi-De** [comment]
This is fixable with an interactive rebase

**Comment by oliverandrich** [comment]
Oh, I haven't noticed it and continued with a release. Well, may be the first day feeling better after Covid-19 is not the best day to fiddle around with git. :) But I can deal with a little mess.

**Comment by Tobi-De** [comment]
>  Well, may be the first day feeling better after Covid-19 is not the best day to fiddle around with git.

Sorry to hear that :( I hope you recover quickly.

> But I can deal with a little mess.
Ok then

**Pull request merged**
